using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using BUS;
namespace QuanLyBanHang
{
    public partial class frmSuaKhachHang : DevExpress.XtraEditors.XtraForm
    {
        string customer_group_id;
        string customer_type_id;
        public frmSuaKhachHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
        }

        private void radioButton2_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void frmThamKhachHang_Load(object sender, EventArgs e)
        {
            tbMa.Enabled = false;
            var cg = CUSTOMER_GROUPBUS.list();
            var tp = Customer_TypeBUS.list();
            // TODO: This line of code loads data into the 'quanLyBanHangDataSet.CUSTOMER_GROUP' table. You can move, or remove it, as needed.
            gvKhuVuc.Properties.DataSource = cg;
            gvKhuVuc.Properties.DisplayMember = "Customer_Group_Name";
            gvKhuVuc.Properties.ValueMember = "Customer_Group_ID";
            gridLookUpEdit1.Properties.DataSource = tp;
            gridLookUpEdit1.Properties.DisplayMember = "Customer_Type_Name";
            gridLookUpEdit1.Properties.ValueMember = "Customer_Type_ID";

        }

        private void btnLuu_Click(object sender, EventArgs e)
        {
            bool a;
            if (!cbActive.Checked)
            {
                a = false;
            }
            else
            {
               a = true;
            }
            CustomerBUS.editByID(tbMa.Text, customer_group_id, tbTen.Text, tbDiaChi.Text, customer_type_id, tbEmail.Text, tbDienThoai.Text, a);

            this.Close();

        }
        
        public void gvKhuVuc_EditValueChanged(object sender, EventArgs e)
        {
            customer_group_id = CUSTOMER_GROUPBUS.objectToDTO(gvKhuVuc.GetSelectedDataRow()).Customer_Group_ID;
        }

        private void gridLookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {
            customer_type_id = Customer_TypeBUS.objectToDTO(gridLookUpEdit1.GetSelectedDataRow()).Customer_Type_ID;
        }

        private void btnDong_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}