using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DAO.AppData;
namespace QuanLyBanHang
{
    public partial class frmThamKhachHang : DevExpress.XtraEditors.XtraForm
    {
        CUSTOMER_GROUP item;
        CUSTOMER_TYPE item1;
        public frmThamKhachHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
        }

        private void radioButton2_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void frmThamKhachHang_Load(object sender, EventArgs e)
        {
            QuanLyBanHangEntities db = new QuanLyBanHangEntities();
            List<CUSTOMER_GROUP> cg = new List<CUSTOMER_GROUP>();
            cg = db.CUSTOMER_GROUP.ToList();
            List<CUSTOMER_TYPE> tp = new List<CUSTOMER_TYPE>();
            tp = db.CUSTOMER_TYPE.ToList();
            // TODO: This line of code loads data into the 'quanLyBanHangDataSet.CUSTOMER_GROUP' table. You can move, or remove it, as needed.
            gvKhuVuc.Properties.DataSource = cg;
            gvKhuVuc.Properties.DisplayMember = "Customer_Group_Name";
            gvKhuVuc.Properties.ValueMember = "Customer_Group_ID";
            gridLookUpEdit1.Properties.DataSource = tp;
            gridLookUpEdit1.Properties.DisplayMember = "Customer_Type_Name";
            gridLookUpEdit1.Properties.ValueMember = "Customer_Type_ID";


        }

        private void btnLuu_Click(object sender, EventArgs e)
        {
            QuanLyBanHangEntities db = new QuanLyBanHangEntities();
            CUSTOMER kh = new CUSTOMER();
            kh.Customer_ID = tbMa.Text;
            kh.CustomerName = tbTen.Text;

            kh.Customer_Type_ID = item1.Customer_Type_ID;
            kh.Customer_Group_ID = item.Customer_Group_ID;
            kh.CustomerAddress = tbDiaChi.Text;
            kh.Email = tbEmail.Text;
            kh.Tel = tbDienThoai.Text;
            if (cbActive.Checked == true)
            {
                kh.Active = true;
            }
            else kh.Active = false;
            db.CUSTOMERs.Add(kh);
            db.SaveChanges();
            this.Close();
            
        }
        
        public void gvKhuVuc_EditValueChanged(object sender, EventArgs e)
        {
            item = gvKhuVuc.GetSelectedDataRow() as CUSTOMER_GROUP;
        }

        private void gridLookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {
            item1 = gridLookUpEdit1.GetSelectedDataRow() as CUSTOMER_TYPE;
        }

        private void btnDong_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}