//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LOG
    {
        public int Log_ID { get; set; }
        public string IP { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Module { get; set; }
        public string Action_Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
