//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_RULE
    {
        public string Group_ID { get; set; }
        public int Object_ID { get; set; }
        public string Rule_ID { get; set; }
        public Nullable<bool> AllowAdd { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public Nullable<bool> AllowAccess { get; set; }
        public Nullable<bool> AllowPrint { get; set; }
        public Nullable<bool> AllowExport { get; set; }
        public Nullable<bool> AllowImport { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual SYS_GROUP SYS_GROUP { get; set; }
        public virtual SYS_OBJECT SYS_OBJECT { get; set; }
    }
}
