//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_OBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_OBJECT()
        {
            this.SYS_USER_RULE = new HashSet<SYS_USER_RULE>();
        }
    
        public int Object_ID { get; set; }
        public string ObjectName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_USER_RULE> SYS_USER_RULE { get; set; }
    }
}
