//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string Customer_ID { get; set; }
        public string CustomerName { get; set; }
        public string Customer_Type_ID { get; set; }
        public string Customer_Group_ID { get; set; }
        public string CustomerAddress { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual CUSTOMER_GROUP CUSTOMER_GROUP { get; set; }
        public virtual CUSTOMER_TYPE CUSTOMER_TYPE { get; set; }
    }
}
