//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public string Stock_ID { get; set; }
        public string StockName { get; set; }
        public string StockAddress { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
