//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public string Message_ID { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
